name: mitmui
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.8.0

dependencies:
  collection: ^1.19.1
  desktop_lifecycle: ^0.1.1
  desktop_multi_window: ^0.2.1
  dio: ^5.8.0+1
  flutter:
    sdk: flutter
  flutter_resizable_container: ^4.2.0
  flutter_riverpod: ^2.6.1
  go_router: ^16.0.0
  provider: ^6.1.2
  web_socket_channel: ^3.0.3
  window_size: ^0.1.0

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
